//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Recursos.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        public static string accesscontrol_hello {
            get {
                return ResourceManager.GetString("accesscontrol.hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string accesscontrol_login {
            get {
                return ResourceManager.GetString("accesscontrol.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string accesscontrol_logout {
            get {
                return ResourceManager.GetString("accesscontrol.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Determining the session status, please wait....
        /// </summary>
        public static string app_authorizing {
            get {
                return ResourceManager.GetString("app.authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to GENOTEC, solution to manage Trials.
        /// </summary>
        public static string app_notauthorized_header {
            get {
                return ResourceManager.GetString("app.notauthorized.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, login to access to the features of the solution..
        /// </summary>
        public static string app_notauthorized_p {
            get {
                return ResourceManager.GetString("app.notauthorized.p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, there is nothing in this section..
        /// </summary>
        public static string app_notfound {
            get {
                return ResourceManager.GetString("app.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Logger.
        /// </summary>
        public static string bitacora_titulo {
            get {
                return ResourceManager.GetString("bitacora.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cardio records.
        /// </summary>
        public static string cardio_titulo {
            get {
                return ResourceManager.GetString("cardio.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Clinical Trial.
        /// </summary>
        public static string ensayo_crear_titulo {
            get {
                return ResourceManager.GetString("ensayo.crear.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Clinical Trial.
        /// </summary>
        public static string ensayo_editar_titulo {
            get {
                return ResourceManager.GetString("ensayo.editar.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Trials.
        /// </summary>
        public static string ensayos_grilla {
            get {
                return ResourceManager.GetString("ensayos.grilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Trials.
        /// </summary>
        public static string ensayos_titulo {
            get {
                return ResourceManager.GetString("ensayos.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string index_welcome {
            get {
                return ResourceManager.GetString("index.welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string main_about {
            get {
                return ResourceManager.GetString("main.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logger.
        /// </summary>
        public static string navmenu_bitacora {
            get {
                return ResourceManager.GetString("navmenu.bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trial.
        /// </summary>
        public static string navmenu_ensayos {
            get {
                return ResourceManager.GetString("navmenu.ensayos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string navmenu_inicio {
            get {
                return ResourceManager.GetString("navmenu.inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patients.
        /// </summary>
        public static string navmenu_pacientes {
            get {
                return ResourceManager.GetString("navmenu.pacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports.
        /// </summary>
        public static string navmenu_reportes {
            get {
                return ResourceManager.GetString("navmenu.reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treatments.
        /// </summary>
        public static string navmenu_tratamientos {
            get {
                return ResourceManager.GetString("navmenu.tratamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPO2 records.
        /// </summary>
        public static string oxigeno_titulo {
            get {
                return ResourceManager.GetString("oxigeno.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new patient.
        /// </summary>
        public static string pacientes_crear_titulo {
            get {
                return ResourceManager.GetString("pacientes.crear.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit patient.
        /// </summary>
        public static string pacientes_editar_titulo {
            get {
                return ResourceManager.GetString("pacientes.editar.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patients list.
        /// </summary>
        public static string pacientes_grilla {
            get {
                return ResourceManager.GetString("pacientes.grilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage patients.
        /// </summary>
        public static string pacientes_titulo {
            get {
                return ResourceManager.GetString("pacientes.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trial Report.
        /// </summary>
        public static string reportes_titulo {
            get {
                return ResourceManager.GetString("reportes.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature records.
        /// </summary>
        public static string temperatura_titulo {
            get {
                return ResourceManager.GetString("temperatura.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Treatment.
        /// </summary>
        public static string tratamiento_crear_titulo {
            get {
                return ResourceManager.GetString("tratamiento.crear.titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treatment list.
        /// </summary>
        public static string tratamientos_grilla {
            get {
                return ResourceManager.GetString("tratamientos.grilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Treatments.
        /// </summary>
        public static string tratamientos_titulo {
            get {
                return ResourceManager.GetString("tratamientos.titulo", resourceCulture);
            }
        }
    }
}
